# Generated by Django 4.2.3 on 2023-07-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='items',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.wishlist'),
            preserve_default=False,
        ),
    ]
