# Generated by Django 4.2.2 on 2023-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
