# Generated by Django 4.2.2 on 2023-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
