# Generated by Django 4.2.3 on 2023-07-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_show_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_choices',
        ),
    ]
