# Generated by Django 4.2.3 on 2023-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_user_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='svg_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
