# Generated by Django 4.2.3 on 2023-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimage_svg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='svg_image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/svg/'),
        ),
    ]
